apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: WRITE_HERE # Place the same namespace that the application will use rabbitmq
  labels:
    app: rabbitmq
    version: "3.8.8"
    component: queue
    part-of: appsbots
spec:
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: cluster-rpc
    port: 25672
    protocol: TCP
    targetPort: 25672
  selector:
    app: rabbitmq
  type: ClusterIP
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  namespace: WRITE_HERE # Place the same namespace that the application will use rabbitmq
  name: rabbitmq-svc
  labels:
    app: rabbitmq
    version: "3.8.8"
    component: queue
    part-of: appsbots
spec:
  type: ClusterIP
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  selector:
    app: rabbitmq
    component: queue

# --- TEST ---
# kind: Service
# apiVersion: v1
# metadata:
#   namespace: WRITE_HERE # Place the same namespace that the application will use rabbitmq
#   name: rabbitmq-client
#   labels:
#     app: rabbitmq
#     type: LoadBalancer
# spec:
#   type: LoadBalancer
#   ports:
#    - name: http
#      protocol: TCP
#      port: 15672
#    - name: prometheus
#      protocol: TCP
#      port: 15692
#    - name: amqp
#      protocol: TCP
#      port: 5672
#   selector:
#     app: rabbitmq